version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Instalando dependências"
      - pip install dbt-core dbt-postgres boto3 awscli
      - apt-get update && apt-get install -y unzip

  pre_build:
    commands:
      - echo "Criando diretório do dbt"
      - mkdir -p /root/.dbt

      - echo "Criando profiles.yml do dbt"
      - |
        cat > /root/.dbt/profiles.yml <<'EOF'
dbt_project:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "redshift-workgroup.540477486035.us-east-1.redshift-serverless.amazonaws.com"
      user: "awsadmin"
      password: "*W*-.TbQtC9gVUkjrAH*"
      dbname: "dev"
      schema: public
      port: 5439
      threads: 4
EOF

      - echo "Definindo DBT_PROFILES_DIR"
      - export DBT_PROFILES_DIR=/root/.dbt

  build:
    commands:
      - echo "Executando dbt run"
      - dbt run
      - dbt test

      - echo "Instalando Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/

      - echo "Executando Terraform"
      - terraform init
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Pipeline finalizado com sucesso"
