version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Instalando dependências"
      - pip install dbt-core dbt-postgres boto3 awscli

      - echo "Instalando Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - echo "Preparando ambiente dbt"
      - mkdir -p ~/.dbt
      - cp profiles.yml ~/.dbt/profiles.yml
      - export DBT_PROFILES_DIR=~/.dbt

  build:
    commands:
      - echo "Executando dbt run"
      - dbt run

      - echo "Executando dbt test"
      - dbt test

      - echo "Executando Terraform"
      - terraform init
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Pipeline finalizado com sucesso"
