version: 2

sources:
  - name: bronze
    database: dev
    schema: spectrum_bronze

    tables:
      - name: at
      - name: eventos

    
  - name: redshift
    database: dev
    schema: public

    tables:
      - name: clientes